export const NAME = 'Nicole'
export const LEGAL_NAME = 'Roman'
export const SURNAME = 'Zubin'

export const EMAIL = 'utkabulka@gmail.com'
export const PHONE_NUMBER = '+995 591 06 90 84'
export const LOCATION = 'Tbilisi, Georgia'
export const LINK_LINKEDIN = 'linkedin.com/in/anxiouscupcake'
export const LINK_GITHUB = 'github.com/anxiouscupcake'

export const PATH_CONTACTS = 'contacts'
export const PATH_RESUME = 'resume'
export const PATH_PORTFOLIO = 'portfolio'
export const PATH_BLOCKY_PARKOUR = 'blocky_parkour'
export const PATH_CALORIE_TRACKER = 'honest_calorie'
